version: 0.2

phases:
  pre_build:
    commands:
      - aws --region $AWS_DEFAULT_REGION ecr get-login-password | docker login --username AWS --password-stdin $ECR_URI

  build:
    commands:
      - docker build -t wordpress:latest .
      - docker tag wordpress:latest $ECR_URI:latest

  post_build:
    commands:
      - docker push $ECR_URI:latest
      - printf '{"ImageURI":"%s:latest"}' $ECR_URI > imageDetail.json
      - CURRENT_TASK_DEFINITION_ARN=$(aws ecs describe-task-definition --task-definition ECSTaskDefinition --query taskDefinition.taskDefinitionArn --output text)
      - CURRENT_REVISION=$(echo $CURRENT_TASK_DEFINITION_ARN | awk -F ':' '{print $7}')
      - NEW_REVISION=$((CURRENT_REVISION + 1))
      - NEW_TASK_DEFINITION_ARN=$(echo $CURRENT_TASK_DEFINITION_ARN | sed "s/:${CURRENT_REVISION}$/:${NEW_REVISION}/")
      - sed -i "s|<TASK_DEFINITION>|${CURRENT_TASK_DEFINITION_ARN}|g" appspec.yaml

artifacts:
  files:
    - imageDetail.json
    - taskdef.json
    - appspec.yaml